### ISSUE TITLE
Assertion error in fread

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#1117]
```
import datatable as dt
d0 = dt.fread("https://archive.ics.uci.edu/ml/machine-learning-databases/entree-mld/entree.data.html", verbose=True)
```
produces:
```
[1] Prepare for reading
  Input is a URL.
  Using default 8 threads
  sep = <auto-detect>
  Decimal separator = '.'
  Quote char = (")
  show_progress = True
  na_strings = ["NA"]
  strip_whitespace = True
  skip_blank_lines = False
  File "/var/folders/k9/mxm_jrl50m75kmgvdk9_wlh00000gp/T/tmpnh0x8a1e/tmp8ds903dl" opened, size: 8164
  ==== file sample ====
  <!------------------------------------------------------------------------
  <!  Entree Chicago Recommendation Data
  <!----------------------------------------------------------------------->
  <HTML>
  <HEAD>
  =====================
  LF character (\n) found in input, \r-only newlines will not be recognized
[2] Detect separator, quoting rule, and ncolumns
  sep=',' with 2 lines of 2 fields using quote rule 0
  sep=' ' with 5 lines of 4 fields using quote rule 0
  sep=' ' detected, setting fill to True
  Detected 74 columns
  sep = ' '
  Quote rule = 0
[3] Detect column types and header
  Number of threads reduced to 1 because data is small
  Number of sampling jump points = 1 because the first chunk was 2.0 times smaller than the entire file
  Type codes (jump 000): ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
  `header` determined to be False because some of the fields on the first row are not of the string type
  =====
  Sampled 101 rows (handled \n inside quoted fields) at 1 jump point(s)
  Bytes from first data row to the end of last row: 8164
  Line length: mean=41.16 sd=64.86 min=1 max=499
  Estimated number of rows: 8164 / 41.16 = 199
  Initial alloc = 398 rows (199 + 100%) using bytes/max(mean-2*sd,min) clamped between [1.1*estn, 2.0*estn]
  All rows were sampled since file is small so we know nrows=101 exactly
  =====
[5] Apply user overrides on column types
  After 0 type and 0 drop user overrides : ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
  Allocating 74 column slots with 101 rows
[6] Read the data
  Number of threads reduced to 1 because data is small
  Too few rows allocated, reallocating to 218 rows
used_nrows!=0 in ~LocalParseContext()
  Removing temporary file /var/folders/k9/mxm_jrl50m75kmgvdk9_wlh00000gp/T/tmpnh0x8a1e/tmp8ds903dl
Traceback (most recent call last):
  File "temp/z.py", line 5, in <module>
    d0 = dt.fread("https://archive.ics.uci.edu/ml/machine-learning-databases/entree-mld/entree.data.html", verbose=True)
  File "/Users/pasha/py36/lib/python3.6/site-packages/datatable/fread.py", line 69, in fread
    return freader.read()
  File "/Users/pasha/py36/lib/python3.6/site-packages/datatable/fread.py", line 729, in read
    _dt = core.gread(self)
RuntimeError: Attempt to write at pos=0 chunk of length 442, however the buffer is allocated for 408 bytes only
```

**Comment by st-pasha** [comment]
Similar error when reading a file from this dataset:
https://archive.ics.uci.edu/ml/machine-learning-databases/00359/NewsAggregatorDataset.zip
```
>>> dt.fread("~/Downloads/NewsAggregatorDataset.zip/newsCorpora.csv", verbose=True)
[1] Prepare for reading
  Input is assumed to be a file name.
  Extracting /Users/pasha/Downloads/NewsAggregatorDataset.zip to temporary directory /var/folders/k9/mxm_jrl50m75kmgvdk9_wlh00000gp/T/tmp8qq27k6w
  Using default 8 threads
  sep = <auto-detect>
  Decimal separator = '.'
  Quote char = (")
  show_progress = True
  na_strings = ["NA"]
  strip_whitespace = True
  skip_blank_lines = False
  File "/var/folders/k9/mxm_jrl50m75kmgvdk9_wlh00000gp/T/tmp8qq27k6w/newsCorpora.csv" opened, size: 102297000
  ==== file sample ====
  1\tFed official says weak data caused by weather, should not slow taper\thttp://www.latimes.com/b...
  2\tFed's Charles Plosser sees high bar for change in pace of tapering\thttp://www.livemint.com/Po...
  3\tUS open: Stocks fall after Fed official hints at accelerated tapering\thttp://www.ifamagazine....
  4\tFed risks falling 'behind the curve', Charles Plosser says\thttp://www.ifamagazine.com/news/fe...
  5\tFed's Plosser: Nasty Weather Has Curbed Job Growth\thttp://www.moneynews.com/Economy/federal-r...
  =====================
  LF character (\n) found in input, \r-only newlines will not be recognized
[2] Detect separator, quoting rule, and ncolumns
  sep=',' with 3 lines of 2 fields using quote rule 0
  sep='\x09' with 100 lines of 8 fields using quote rule 0
  Detected 8 columns
  sep = '\x09'
  Quote rule = 0
[3] Detect column types and header
  Number of sampling jump points = 101 because the first chunk was 4348.1 times smaller than the entire file
  Type codes (jump 000): issssssI
  `header` determined to be False because some of the fields on the first row are not of the string type
  =====
  Sampled 101 rows (handled \n inside quoted fields) at 101 jump point(s)
  Bytes from first data row to the end of last row: 102297000
  Line length: mean=232.99 sd=43.65 min=162 max=322
  Estimated number of rows: 102297000 / 232.99 = 439062
  Initial alloc = 631462 rows (439062 + 43%) using bytes/max(mean-2*sd,min) clamped between [1.1*estn, 2.0*estn]
  =====
[5] Apply user overrides on column types
  After 0 type and 0 drop user overrides : issssssI
  Allocating 8 column slots with 631462 rows
[6] Read the data
  Removing temporary file /var/folders/k9/mxm_jrl50m75kmgvdk9_wlh00000gp/T/tmp8qq27k6w/newsCorpora.csv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pasha/github/datatable/datatable/fread.py", line 69, in fread
    return freader.read()
  File "/Users/pasha/github/datatable/datatable/fread.py", line 729, in read
    _dt = core.gread(self)
RuntimeError: Attempt to write at pos=2515484 chunk of length 104242, however the buffer is allocated for 2525852 bytes only
```
as reported in https://github.com/h2oai/h2oai/issues/3809
