### ISSUE TITLE
Updating a column in a frame may fail with "Only views can be materialized" error

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#1225]
There is no repro case yet, but it happens when you have a Frame where only 1 column out of all is a view, and then one tries to update another column through `frame[col] = newcol`, which attempts to do `_dt.materialize()` internally.

**Comment by st-pasha** [comment]
Repro:
```Python
import datatable as dt
from datatable import f
f0 = dt.Frame(A=[1,2,3], B=[5,6,8])
f1 = f0[::-1, :][:, {"A": dt.float64(f.A), "B": f.B}]
assert f1.internal.isview
f1.materialize()
```
results in
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pasha/github/datatable/datatable/frame.py", line 911, in materialize
    self._dt = self._dt.materialize()
ValueError: Only a view can be materialized
```
