### ISSUE TITLE
RA failure on seed=5474131906442374464

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#1290]
```
---- STDOUT -----------------------------------------
Making a frame with nrows=140, ncols=1
  types: bool=0, int=1, float=0, str=0
  missing values: 0.000
Launching an attack for 6 rounds
[02] Applying row slice (None, 128, 2) -> nrows = 64
[02] Applying row slice (6, None, 7) -> nrows = 9
[02] Applying row slice (1, None, 1) -> nrows = 8
[01] Setting nrows to 5
[02] Applying row slice (None, 0, -1) -> nrows = 4
[01] Setting nrows to 3
Attack end, checking the outcome

---- STDERR -----------------------------------------
Traceback (most recent call last):
  File "random_attack.py", line 400, in <module>
    ra.attack()
  File "random_attack.py", line 39, in attack
    frame.check()
  File "random_attack.py", line 286, in check
    self.df.internal.check()
AssertionError: Invalid min/max values in a Slice RowIndex 82/3/-14: min = 40, max = 82
```

**Comment by st-pasha** [comment]
MRE:
```
>>> import datatable as dt
>>> f0 = dt.Frame(range(25))
>>> f1 = f0[::2, :]
>>> f1.nrows = 3
>>> f1.internal.check()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: Invalid min/max values in a Slice RowIndex 0/3/2: min = 0, max = 24
```
