### ISSUE TITLE
improve .to_pandas() error handling

### ISSUE THREAD

**Issue by jangorecki** [h2oai/datatable#1402]
I am getting an error when trying to
```
>>> x = dt.fread(src_grp).to_pandas()
Traceback (most recent call last):                                              
  File "<stdin>", line 1, in <module>
  File "/home/jan/git/db-benchmark/pydatatable/py-pydatatable/lib/python3.6/site-packages/datatable/frame.py", line 455, in topandas
    pd = pandas.DataFrame(srccols)
AttributeError: module 'pandas' has no attribute 'DataFrame'
```
before trying to use pandas module datatable could check if it is possible and raise appropriate error.

**Comment by jangorecki** [comment]
I think that pandas were simply not available in that virtual env

**Comment by st-pasha** [comment]
If there is no pandas at all, the error will be
```
>>> dt.Frame(range(10)).to_pandas()
ImportError: Module pandas is not installed. It is required for running this function.
```
