### ISSUE TITLE
Cannot install from source distribution

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/datatable#1451]
```
c:\h2oai>pip install datatable
Collecting datatable
  Downloading https://files.pythonhosted.org/packages/0b/b6/323297afd7258e7960f474cc256dd988a2bb923109adf87445435edbe575/datatable-0.7.0.tar.gz (526kB)
    100% |████████████████████████████████| 532kB 1.3MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Jon\AppData\Local\Temp\pip-install-uuyu508q\datatable\setup.py", line 18, in <module>
        from ci.setup_utils import (get_datatable_version, make_git_version_file,
    ModuleNotFoundError: No module named 'ci'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Jon\AppData\Local\Temp\pip-install-uuyu508q\datatable\
```

Why is ci = continuous integration something needed for datatable as a application?  Should only be for testing.  And any solution otherwise?

**Comment by pseudotensor** [comment]
Using windows python 3.6.2.

**Comment by st-pasha** [comment]
`datatable` cannot be currently installed on windows, see #1114
However, the error message should be different than what you see. I'll need to investigate this.

**Comment by sizrailev-ias** [comment]
For the record, the same error occurs when installing on Ubuntu 16.04 (with Python 3.7.2 on AWS with the DAI 1.5.0 AMI).
