### ISSUE TITLE
Internal error when `j` refers to a g-column but there is no join

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#1481]
```
>>> import datatable as dt
>>> from datatable import f, g
>>> df = dt.Frame(A=range(5))
>>> df[:, [f.A, g.A]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pasha/github/datatable/datatable/graph/__init__.py", line 44, in make_datatable
    colsnode = make_columnset(select, ee, update_mode)
  File "/Users/pasha/github/datatable/datatable/graph/cols_node.py", line 345, in make_columnset
    pcol.resolve()
  File "/Users/pasha/github/datatable/datatable/expr/column_expr.py", line 37, in resolve
    self._colid = dt.colindex(self._colexpr)
AttributeError: 'NoneType' object has no attribute 'colindex'
```

Low priority, since the expression `df[:, [f.A, g.A]]` is erroneous anyways, we just need to emit a better error message to the user.

**Comment by st-pasha** [comment]
When `g.` column is used in `i` node, a seg.fault may occur...
