### ISSUE TITLE
Installing with pip on MacOS requires llvm

### ISSUE THREAD

**Issue by g-eoj** [h2oai/datatable#1559]
- Did you find a bug in datatable, or maybe the bug found you?
  Following the install instructions for MacOS doesn't work unless llvm is installed.

- How to reproduce the bug?
Install with `pip install datatable` on MacOS. Then run python and import datatables. I'm using conda but I don't think it makes a difference because it still looks for `/usr/local/opt/llvm/lib/libomp.dylib`, see below.

```
(dt) MBP15:~ user$ python
Python 3.7.1 (default, Dec 14 2018, 13:28:58)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import datatable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/miniconda3/lib/python3.7/site-packages/datatable/__init__.py", line 8, in <module>
    from .dt_append import rbind, cbind
  File "/Users/user/miniconda3/lib/python3.7/site-packages/datatable/dt_append.py", line 8, in <module>
    from datatable.utils.misc import plural_form as plural
  File "/Users/user/miniconda3/lib/python3.7/site-packages/datatable/utils/misc.py", line 8, in <module>
    from .typechecks import TImportError
  File "/Users/user/miniconda3/lib/python3.7/site-packages/datatable/utils/typechecks.py", line 15, in <module>
    from datatable.lib import core
  File "/Users/user/miniconda3/lib/python3.7/site-packages/datatable/lib/__init__.py", line 9, in <module>
    from . import _datatable as core
ImportError: dlopen(/Users/user/miniconda3/lib/python3.7/site-packages/datatable/lib/_datatable.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/llvm/lib/libomp.dylib
  Referenced from: /Users/user/miniconda3/lib/python3.7/site-packages/datatable/lib/_datatable.cpython-37m-darwin.so
  Reason: image not found
```
I fixed the error by installing llvm with brew.

- What was the expected behavior?
Install instructions don't mention the llvm requirement. It's unclear whether this is expected behavior or not.

- Your environment?
datatable version: 0.7.0
python version: 3.7.1
operating system: MacOS 10.14.2

**Comment by st-pasha** [comment]
Can you please post your `pip install` logs, so that it's clear how it is being installed?

**Comment by st-pasha** [comment]
Ok, I was able to confirm the problem.

In the meanwhile, you can try the following fix on your local machine (run from the command line):
```bash
$ install_name_tool -change /usr/local/opt/llvm/lib/libomp.dylib @rpath/libomp.dylib /Users/user/miniconda3/lib/python3.7/site-packages/datatable/lib/_datatable.cpython-37m-darwin.so
```
