### ISSUE TITLE
LC_ALL=POSIX seems like it is not supported

### ISSUE THREAD

**Issue by mmalohlava** [h2oai/datatable#1662]
- Did you find a bug in datatable, or maybe the bug found you?
  Tell us what it is.

- How to reproduce the bug?
0. Create Ubuntu18.04 docker image
```
FROM ubuntu:18.04

COPY ./dai_1.6.0_amd64.deb /

RUN dpkg -i /dai_1.6.0_amd64.deb || true

ENV LC_ALL=POSIX
```

by running `docker build -t ubuntu18 -f Dockerfile .`

1. Run `./dai-env.sh python` in created container 
2. Run `import datatable`
3. Explore stacktrace
```
>>> import datatable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/h2oai/dai/python/lib/python3.6/site-packages/datatable/__init__.py", line 24, in <module>
    from .dt_append import rbind, cbind
  File "/opt/h2oai/dai/python/lib/python3.6/site-packages/datatable/dt_append.py", line 8, in <module>
    from datatable.utils.misc import plural_form as plural
  File "/opt/h2oai/dai/python/lib/python3.6/site-packages/datatable/utils/misc.py", line 8, in <module>
    from .typechecks import TImportError
  File "/opt/h2oai/dai/python/lib/python3.6/site-packages/datatable/utils/typechecks.py", line 14, in <module>
    from datatable.utils.terminal import term
  File "/opt/h2oai/dai/python/lib/python3.6/site-packages/datatable/utils/terminal.py", line 89, in <module>
    term = MyTerminal()
  File "/opt/h2oai/dai/python/lib/python3.6/site-packages/datatable/utils/terminal.py", line 20, in __init__
    super().__init__()
  File "/opt/h2oai/dai/python/lib/python3.6/site-packages/blessed/terminal.py", line 229, in __init__
    self.__init__keycodes()
  File "/opt/h2oai/dai/python/lib/python3.6/site-packages/blessed/terminal.py", line 287, in __init__keycodes
    locale.setlocale(locale.LC_ALL, '')
  File "/opt/h2oai/dai/python/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by st-pasha** [comment]
The error is thrown from the following code in "_localemodule.c":
```C
        /* set locale */
        result = setlocale(category, locale);
        if (!result) {
            /* operation failed, no setting was changed */
            PyErr_SetString(Error, "unsupported locale setting");
            return NULL;
        }
```
where `setlocale()` function is imported from C header "locale.h". So basically this locale is not supported at OS level. The docs for this function (https://en.cppreference.com/w/c/locale/setlocale) say that

> POSIX also defines a locale named "POSIX", which is always accessible and is exactly equivalent to the default minimal "C" locale.

So, it appears your Ubuntu installation is not quite POSIX-compliant... The workaround though is simple: use `"C"` locale (which is always available) instead of `"POSIX"`. Also try `locale -a` to list all available locales.

**Comment by mmalohlava** [comment]
FYI:

```
root@3793775df8dd:/# locale -a
C
C.UTF-8
POSIX
```

**Comment by mmalohlava** [comment]
Cannot repro any more in docker, so closing for now - seems it was caused by some leak in environment.
