### ISSUE TITLE
core dumped during fread

### ISSUE THREAD

**Issue by arnocandel** [h2oai/datatable#1961]
`0.9.0.dev119` f030c69175c4da1268b342bc2189c666b3637313
```
Core was generated by `/home/arno/h2oai/env/bin/python -u -c import sys;exec(eval(sys.stdin.readline()'.
Program terminated with signal SIGBUS, Bus error.
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:249
249	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
[Current thread is 1 (Thread 0x7ff3b2d03700 (LWP 6849))]
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:249
#1  0x00007ff3f97de250 in ThreadsafeWritableBuffer::write_at (this=0x4c81120, pos=4754125, n=321152, src=0x82fcf40) at c/writebuf.cc:177
#2  0x00007ff3f98d619c in dt::write::write_manager::__lambda2::__lambda5::operator() (__closure=0x7ffce5ca19a0) at c/write/write_manager.cc:136
#3  dt::function<void(long unsigned int)>::callback_fn<dt::write::write_manager::write_rows()::__lambda2::__lambda5>(dt::function<void(long unsigned int)>::fptr, unsigned long) (callable=0x7ffce5ca19a0, 
    params#0=<optimized out>) at c/utils/function.h:55
#4  0x00007ff3f98f647b in dt::function<void (unsigned long)>::operator()(unsigned long) const (params#0=<optimized out>, this=0x4f35788) at c/utils/function.h:72
#5  dt::ordered_task::execute (this=0x4f35760) at c/parallel/parallel_for_ordered.cc:102
#6  0x00007ff3f98f5a9f in dt::thread_worker::run (this=0x287b770) at c/parallel/thread_worker.cc:71
#7  0x00007ff3f941c9e0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ff4025a56db in start_thread (arg=0x7ff3b2d03700) at pthread_create.c:463
#9  0x00007ff4028de88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
core file: https://slack-files.com/T0329MHH6-FMCE0018U-d5246fda0c

**Comment by arnocandel** [comment]
never mind - user error. file was being overwritten by separate process.
