### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by leo-filgueira** [h2oai/datatable#1982]
I'm trying to install the package in a ubuntu machine and I'm running Python 3.7.3. 

First I tried following [this page](https://datatable.readthedocs.io/en/latest/install.html). The message is: `datatable-0.8.0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform`.

Then, I tried following [pypi page](https://pypi.org/project/datatable/) and the message is: `Could not find a version that satisfies the requirement datatable (from versions: )
No matching distribution found for datatable`

**Comment by st-pasha** [comment]
Could you please post the output from `pip install datatable -vvv`, maybe it'll be possible to discern the problem from the logs.

**Comment by leo-filgueira** [comment]
```
Created temporary directory: /tmp/pip-ephem-wheel-cache-bV3u2F
Created temporary directory: /tmp/pip-req-tracker-VL81DM
Created requirements tracker '/tmp/pip-req-tracker-VL81DM'
Created temporary directory: /tmp/pip-install-py0qjz
Collecting datatable
  1 location(s) to search for versions of datatable:
  * https://pypi.org/simple/datatable/
  Getting page https://pypi.org/simple/datatable/
  Looking up "https://pypi.org/simple/datatable/" in the cache
  Current age based on date: 76567
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 0
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/datatable/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/datatable/
    Skipping link https://files.pythonhosted.org/packages/a0/c4/fb925a263ab65f4706e0f06e6e31a8c3a57f2cc07ec7f16eef53bb1b57f3/datatable-0.3.0-cp35-cp35m-macosx_10_6_x86_64.whl#sha256=89382ed20cd4d90796d40e5696cacea11f0732727d68a2d40e572cb53baa0ad8 (from https://pypi.org/simple/datatable/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/f5/df/08d765bff48d8f2630314eb5b6e703798f765a9952c0a94495a05ea13ffd/datatable-0.3.1-cp35-cp35m-macosx_10_6_x86_64.whl#sha256=f7613fe57204f1b2bb8d1700a8adba853bbb8297cdebd4ac6b9768777423d067 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/95/f6/4798ab9418eecea6adb6f060f27e254c6a185352e8a4539ee6c64d5efe8c/datatable-0.3.1-cp36-cp36m-macosx_10_6_intel.whl#sha256=dd03ffd71104b47da8808ee7ed279ea44357a9c4bbfc468b7dc6d4a2e08c4b1d (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/fd/98/a881ebd763f8785c4df59518f67f3703c7194f496040c9a472982fb8544d/datatable-0.3.1.tar.gz#sha256=f37eda31d581fe266684a0adeea581f379615751f1b7ef1270b65fb065315fa9 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    Skipping link https://files.pythonhosted.org/packages/7b/35/0f6ec6f8cdf97a1334a4d612382444cd8406df967afee1b8d359239561d2/datatable-0.3.2-cp35-cp35m-macosx_10_6_x86_64.whl#sha256=9a6d19a0b9891bc3f5bd8cb3ea55111f90a4a52a0474960d79f14458ad80dca7 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/b0/d0/2727e2355c748435fa5407a25b12c69c1ed72e644bad6a532f03131237fc/datatable-0.3.2-cp36-cp36m-macosx_10_6_intel.whl#sha256=3c0c394d5e1af9d13bb4db3f5b49647d58768ab518ac4350f86e6666c392df29 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/82/ca/5690f19c149874de9a23ae9fc25f787269c4023d39fdb48ab1f815e863d5/datatable-0.3.2.tar.gz#sha256=ec3a57521b8856ba19aae1cd83322220257b34a8dc9a89a66c0a2d4c477fd58e (from https://pypi.org/simple/datatable/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    The package https://files.pythonhosted.org/packages/af/10/5f458bb24545845da3f290179a139f93c9c6966a3817fab9049f930cd5b8/datatable-0.4.0.tar.gz#sha256=2f400223c427a7f61812b28120315e94408119a049479aef213f0d4161ef5822 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    Skipping link https://files.pythonhosted.org/packages/5a/a6/2785bd9ac05ebffb71c067e8e1e0d0e65667482e15c3d1e221e9ebc80c3b/datatable-0.5.0-cp35-cp35m-macosx_10_7_x86_64.whl#sha256=6b771be56bd1cfde531e616ce85c1a1f57436dab362b1d54895bd40e62caf995 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/e5/2a/25e82809675f59e086c98672b570a62ddfd9b062ed954ef0fd8fc2a9a0f2/datatable-0.5.0-cp36-cp36m-macosx_10_6_intel.whl#sha256=d6efe90ef1c6f5c22eb186cb8833950562afdadb3f387d70dc6a77a9e54ecef8 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/0e/cd/d994e4d67867f1ffbfbb355b98e43db5e689507fb785ed11057ea907980a/datatable-0.5.0-cp36-cp36m-macosx_10_7_x86_64.whl#sha256=b230b90b33e307e51830c484214c2cf8d942427b09f7f3359a9f51c4c1a87094 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/09/ac/fd225408382529a4995143ff97c5226c72c8df8057496831256376e0ff9f/datatable-0.5.0.tar.gz#sha256=699f750ee9896db71ef8a58758bae757c8995d473579f8685a82279ebc6ee9c7 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    Skipping link https://files.pythonhosted.org/packages/bd/67/09d6fb031456aec7e03a0a7ee9d904b6528b438b9a48019ed16a60d439dc/datatable-0.6.0-cp35-cp35m-macosx_10_7_x86_64.whl#sha256=ed7b569e83b3a569d9c6fd7a01f4f76c3a584e7d04fefc5066a01715a7d7e1c6 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/14/06/212109e29351a4351a2684e5c8c80bf14744fc2edac008d555b5bcc2de21/datatable-0.6.0-cp36-cp36m-macosx_10_7_x86_64.whl#sha256=878ab3a292a37351071e7e07062a63e67766c9d4718acaa7d0ed9bdc35c0f131 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/41/f1/cbe0dcb4dc513f754cf4ff4e0ab72e16e3aeafc2f44205ba30d28abc8184/datatable-0.6.0.tar.gz#sha256=7861146df1cb087208180bec058614f5b2dc427a0fcf5eb535340d39b9f9fae7 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    Skipping link https://files.pythonhosted.org/packages/4f/ce/edc756fbb3ebf25844faf5cf40e141ad13de8d01a1c44fb5d6451272d91c/datatable-0.7.0-cp35-cp35m-macosx_10_7_x86_64.whl#sha256=a00772f6ccbf04ba2433734686b8e67433c10a0ff5f4f7db898dd78874816184 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/d0/8e/20151d986c342138d390e968b25428697c539c69cd0d6fa0095c18455636/datatable-0.7.0-cp36-cp36m-macosx_10_7_x86_64.whl#sha256=3b47a7d05530cab5e5c932bdb2306b1db7c593774b943a6e80354f3b40f52d2d (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/a1/e4/77e2feba6d0f7475576fd14c92a449e2b3941508aa150f125824a809e284/datatable-0.7.0-cp37-cp37m-macosx_10_7_x86_64.whl#sha256=d8c7143e0156468240c8d6b28b53a35a52919f15d1dc240e301511b1b40ebd51 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/0b/b6/323297afd7258e7960f474cc256dd988a2bb923109adf87445435edbe575/datatable-0.7.0.tar.gz#sha256=97b8a942c542a7d11eb634f1955e3b32906425ed2a6b7c23baa4568949f8fcd8 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    Skipping link https://files.pythonhosted.org/packages/4e/8a/fcbd50c3084398dcdcb38ad7c0f517861517bbf4e80af329c3110df8ad6e/datatable-0.8.0-cp35-cp35m-macosx_10_7_x86_64.whl#sha256=8ac2e58810d531969eec67f606f5030ebf38a263c0822cc5b6bd8ec56d755bf6 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/de/61/3a20a529980d18f1ed2805fd1ccc0c4609ad5ae1dd489c1f80ea58928ef9/datatable-0.8.0-cp36-cp36m-macosx_10_7_x86_64.whl#sha256=30563d9bea59c315c8c0c8299683f86c129ff556e9cbd4f0cc71afe3ef006e16 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/f3/63/f13b22b3a4e220b91e453ebe76e715fd68bb3b0f084fa1b4d1a14b38576e/datatable-0.8.0-cp37-cp37m-macosx_10_7_x86_64.whl#sha256=c8306b4462ce76e84afb102e6f000690fe69e51e5e26af8ba2ca64a63effbcda (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/33/6b/02045aa871501bec23a17563c9fb70782fa5b152b2f03faaf1b147c667e0/datatable-0.8.0.tar.gz#sha256=53e657e07c87b6802633eff5547897bbe977989c17d09c79db9365e77e401fe9 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    Skipping link https://files.pythonhosted.org/packages/ef/d9/447d7361b74c843d865e47c9509f294ea158cfa03b9900ff365130fcdaf5/datatable-0.9.0-cp35-cp35m-macosx_10_7_x86_64.whl#sha256=7ca12f031d6f92cc03638cf0b19cda61f5b8c6e1b452ee951fea7df323d4a139 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/75/a9/acd8d0725460c8370b68a1d0ceb58fe893d57fe3666b1bc0b22ea1b09637/datatable-0.9.0-cp35-cp35m-manylinux2010_x86_64.whl#sha256=878170406819e57cd88df180cc9ea6e7b86f516330fc2b3b0c2b13d50fba0718 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/48/1f/789653311f87794df631abcfb32677292b79cf97de5a4ad1ea19859568e4/datatable-0.9.0-cp36-cp
leonardo@rstudiodev:~/CRM_Inteligence$ pip install datatable -vvv
Created temporary directory: /tmp/pip-ephem-wheel-cache-MqCvVt
Created temporary directory: /tmp/pip-req-tracker-bqJ4I0
Created requirements tracker '/tmp/pip-req-tracker-bqJ4I0'
Created temporary directory: /tmp/pip-install-xP6eAO
Collecting datatable
  1 location(s) to search for versions of datatable:
  * https://pypi.org/simple/datatable/
  Getting page https://pypi.org/simple/datatable/
  Looking up "https://pypi.org/simple/datatable/" in the cache
  Cache entry deserialization failed, entry ignored
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/datatable/ HTTP/1.1" 200 3002
  Updating cache with response from "https://pypi.org/simple/datatable/"
  Caching due to etag
  Analyzing links from page https://pypi.org/simple/datatable/
    Skipping link https://files.pythonhosted.org/packages/a0/c4/fb925a263ab65f4706e0f06e6e31a8c3a57f2cc07ec7f16eef53bb1b57f3/datatable-0.3.0-cp35-cp
35m-macosx_10_6_x86_64.whl#sha256=89382ed20cd4d90796d40e5696cacea11f0732727d68a2d40e572cb53baa0ad8 (from https://pypi.org/simple/datatable/); it is 
not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/f5/df/08d765bff48d8f2630314eb5b6e703798f765a9952c0a94495a05ea13ffd/datatable-0.3.1-cp35-cp
35m-macosx_10_6_x86_64.whl#sha256=f7613fe57204f1b2bb8d1700a8adba853bbb8297cdebd4ac6b9768777423d067 (from https://pypi.org/simple/datatable/) (requir
es-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/95/f6/4798ab9418eecea6adb6f060f27e254c6a185352e8a4539ee6c64d5efe8c/datatable-0.3.1-cp36-cp
36m-macosx_10_6_intel.whl#sha256=dd03ffd71104b47da8808ee7ed279ea44357a9c4bbfc468b7dc6d4a2e08c4b1d (from https://pypi.org/simple/datatable/) (require
s-python:>=3.5); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/fd/98/a881ebd763f8785c4df59518f67f3703c7194f496040c9a472982fb8544d/datatable-0.3.1.tar.gz#sh
a256=f37eda31d581fe266684a0adeea581f379615751f1b7ef1270b65fb065315fa9 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5) is incompati
ble with the pythonversion in use. Acceptable python versions are:>=3.5
    Skipping link https://files.pythonhosted.org/packages/7b/35/0f6ec6f8cdf97a1334a4d612382444cd8406df967afee1b8d359239561d2/datatable-0.3.2-cp35-cp
35m-macosx_10_6_x86_64.whl#sha256=9a6d19a0b9891bc3f5bd8cb3ea55111f90a4a52a0474960d79f14458ad80dca7 (from https://pypi.org/simple/datatable/) (requir
es-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/b0/d0/2727e2355c748435fa5407a25b12c69c1ed72e644bad6a532f03131237fc/datatable-0.3.2-cp36-cp
36m-macosx_10_6_intel.whl#sha256=3c0c394d5e1af9d13bb4db3f5b49647d58768ab518ac4350f86e6666c392df29 (from https://pypi.org/simple/datatable/) (require
s-python:>=3.5); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/82/ca/5690f19c149874de9a23ae9fc25f787269c4023d39fdb48ab1f815e863d5/datatable-0.3.2.tar.gz#sh
a256=ec3a57521b8856ba19aae1cd83322220257b34a8dc9a89a66c0a2d4c477fd58e (from https://pypi.org/simple/datatable/) (requires-python:>=3.5) is incompati
ble with the pythonversion in use. Acceptable python versions are:>=3.5
    The package https://files.pythonhosted.org/packages/af/10/5f458bb24545845da3f290179a139f93c9c6966a3817fab9049f930cd5b8/datatable-0.4.0.tar.gz#sha256=2f400223c427a7f61812b28120315e94408119a049479aef213f0d4161ef5822 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    Skipping link https://files.pythonhosted.org/packages/5a/a6/2785bd9ac05ebffb71c067e8e1e0d0e65667482e15c3d1e221e9ebc80c3b/datatable-0.5.0-cp35-cp35m-macosx_10_7_x86_64.whl#sha256=6b771be56bd1cfde531e616ce85c1a1f57436dab362b1d54895bd40e62caf995 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/e5/2a/25e82809675f59e086c98672b570a62ddfd9b062ed954ef0fd8fc2a9a0f2/datatable-0.5.0-cp36-cp36m-macosx_10_6_intel.whl#sha256=d6efe90ef1c6f5c22eb186cb8833950562afdadb3f387d70dc6a77a9e54ecef8 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/0e/cd/d994e4d67867f1ffbfbb355b98e43db5e689507fb785ed11057ea907980a/datatable-0.5.0-cp36-cp36m-macosx_10_7_x86_64.whl#sha256=b230b90b33e307e51830c484214c2cf8d942427b09f7f3359a9f51c4c1a87094 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/09/ac/fd225408382529a4995143ff97c5226c72c8df8057496831256376e0ff9f/datatable-0.5.0.tar.gz#sha256=699f750ee9896db71ef8a58758bae757c8995d473579f8685a82279ebc6ee9c7 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    Skipping link https://files.pythonhosted.org/packages/bd/67/09d6fb031456aec7e03a0a7ee9d904b6528b438b9a48019ed16a60d439dc/datatable-0.6.0-cp35-cp35m-macosx_10_7_x86_64.whl#sha256=ed7b569e83b3a569d9c6fd7a01f4f76c3a584e7d04fefc5066a01715a7d7e1c6 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/14/06/212109e29351a4351a2684e5c8c80bf14744fc2edac008d555b5bcc2de21/datatable-0.6.0-cp36-cp36m-macosx_10_7_x86_64.whl#sha256=878ab3a292a37351071e7e07062a63e67766c9d4718acaa7d0ed9bdc35c0f131 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/41/f1/cbe0dcb4dc513f754cf4ff4e0ab72e16e3aeafc2f44205ba30d28abc8184/datatable-0.6.0.tar.gz#sha256=7861146df1cb087208180bec058614f5b2dc427a0fcf5eb535340d39b9f9fae7 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    Skipping link https://files.pythonhosted.org/packages/4f/ce/edc756fbb3ebf25844faf5cf40e141ad13de8d01a1c44fb5d6451272d91c/datatable-0.7.0-cp35-cp35m-macosx_10_7_x86_64.whl#sha256=a00772f6ccbf04ba2433734686b8e67433c10a0ff5f4f7db898dd78874816184 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/d0/8e/20151d986c342138d390e968b25428697c539c69cd0d6fa0095c18455636/datatable-0.7.0-cp36-cp36m-macosx_10_7_x86_64.whl#sha256=3b47a7d05530cab5e5c932bdb2306b1db7c593774b943a6e80354f3b40f52d2d (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/a1/e4/77e2feba6d0f7475576fd14c92a449e2b3941508aa150f125824a809e284/datatable-0.7.0-cp37-cp37m-macosx_10_7_x86_64.whl#sha256=d8c7143e0156468240c8d6b28b53a35a52919f15d1dc240e301511b1b40ebd51 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/0b/b6/323297afd7258e7960f474cc256dd988a2bb923109adf87445435edbe575/datatable-0.7.0.tar.gz#sha256=97b8a942c542a7d11eb634f1955e3b32906425ed2a6b7c23baa4568949f8fcd8 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    Skipping link https://files.pythonhosted.org/packages/4e/8a/fcbd50c3084398dcdcb38ad7c0f517861517bbf4e80af329c3110df8ad6e/datatable-0.8.0-cp35-cp35m-macosx_10_7_x86_64.whl#sha256=8ac2e58810d531969eec67f606f5030ebf38a263c0822cc5b6bd8ec56d755bf6 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/de/61/3a20a529980d18f1ed2805fd1ccc0c4609ad5ae1dd489c1f80ea58928ef9/datatable-0.8.0-cp36-cp36m-macosx_10_7_x86_64.whl#sha256=30563d9bea59c315c8c0c8299683f86c129ff556e9cbd4f0cc71afe3ef006e16 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/f3/63/f13b22b3a4e220b91e453ebe76e715fd68bb3b0f084fa1b4d1a14b38576e/datatable-0.8.0-cp37-cp37m-macosx_10_7_x86_64.whl#sha256=c8306b4462ce76e84afb102e6f000690fe69e51e5e26af8ba2ca64a63effbcda (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/33/6b/02045aa871501bec23a17563c9fb70782fa5b152b2f03faaf1b147c667e0/datatable-0.8.0.tar.gz#sha256=53e657e07c87b6802633eff5547897bbe977989c17d09c79db9365e77e401fe9 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
    Skipping link https://files.pythonhosted.org/packages/ef/d9/447d7361b74c843d865e47c9509f294ea158cfa03b9900ff365130fcdaf5/datatable-0.9.0-cp35-cp35m-macosx_10_7_x86_64.whl#sha256=7ca12f031d6f92cc03638cf0b19cda61f5b8c6e1b452ee951fea7df323d4a139 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/75/a9/acd8d0725460c8370b68a1d0ceb58fe893d57fe3666b1bc0b22ea1b09637/datatable-0.9.0-cp35-cp35m-manylinux2010_x86_64.whl#sha256=878170406819e57cd88df180cc9ea6e7b86f516330fc2b3b0c2b13d50fba0718 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/48/1f/789653311f87794df631abcfb32677292b79cf97de5a4ad1ea19859568e4/datatable-0.9.0-cp36-cp36m-macosx_10_7_x86_64.whl#sha256=9169a9bfa8bc3f5d929d81b608d5762156dd82d8775a1a249831cf83e7fdb00a (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/17/27/796081e2f75b482dc18155ef51d559f185d7c0c4e4273047babb58f9e92b/datatable-0.9.0-cp36-cp36m-manylinux2010_x86_64.whl#sha256=73418734c5126165b7b9357c8c289df02ff88837aab7713d5dbb27b40a430463 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/35/96/2430b8562206f1021f2be71f18f25fa3e2ed449c92a71ae2b5ddb7f3dc72/datatable-0.9.0-cp37-cp37m-macosx_10_7_x86_64.whl#sha256=8510479469cb42e021173aebe3b6461e6d946741fdafcb40625244fe983612a2 (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/6f/4d/d11077f5d167826ac224ee06c427fd18104fcc22b4896caa95bd535864ea/datatable-0.9.0-cp37-cp37m-manylinux2010_x86_64.whl#sha256=dc979bfed9fe6bbc9682909186113756bfca505cf4818c930bf288b470ac395e (from https://pypi.org/simple/datatable/) (requires-python:>=3.5); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/4e/83/ef04b3d1340a4b2346c3afe442f94cec66d0e9dad11d8996c75161c8dd20/datatable-0.9.0.tar.gz#sha256=ae986a4fed9f2671f66f269300dfbb23d84b4e6b7c9f62b53252799bea941cea (from https://pypi.org/simple/datatable/) (requires-python:>=3.5) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.5
  Could not find a version that satisfies the requirement datatable (from versions: )
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-bqJ4I0'
No matching distribution found for datatable
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/_internal/commands/install.py", line 338, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python2.7/dist-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python2.7/dist-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python2.7/dist-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/_internal/operations/prepare.py", line 218, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/usr/lib/python2.7/dist-packages/pip/_internal/req/req_install.py", line 164, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/_internal/index.py", line 621, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for datatable
```
This machine has Python 2.7.13 and 3.7.3.

**Comment by st-pasha** [comment]
I see, so your `pip` is tied to `python-2.7`, and therefore it cannot find a "matching distribution". 
I'd recommend creating a new virtual env with python 3.7 and try in that virtualenv. Alternatively, you can run `python3.7 -m pip install datatable`

**Comment by leo-filgueira** [comment]
I tried the alternative suggestion just now, but I got an error again. The first error message is: 
``` 
/usr/include/c++/6/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
   #include_next <stdlib.h>
                           ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for datatable```

**Comment by st-pasha** [comment]
This means the standard C header file "stdlib.h" is not found in the standard system location. I would recommend searching for this file manually and then adding its path in `CC_FLAGS` variable. Or, if the file is missing altogether, try to install it. Frankly, I've never seen a case of standard C includes missing on a Linux distribution, perhaps this is some kind of misconfiguration of gcc?

**Comment by leo-filgueira** [comment]
I'll check this. Thanks

**Comment by leo-filgueira** [comment]
Someone at my work installed. He has installed the package by running `pip install datatable` and it worked.
