### ISSUE TITLE
Creating Frame from a reversed numpy array fails

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#2163]
```
>>> import numpy as np
>>> import datatable as dt
>>> dt.Frame(np.array(range(10))[::-1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pasha/github/datatable/datatable/utils/terminal.py", line 169, in _new_displayhook
    value.view(None)
AssertionError: Assertion 'i < nrows()' failed in c/column.cc, line 188
```

**Comment by st-pasha** [comment]
Also this:
```
>>> import datatable as dt
>>> import datatable.internal
>>> import numpy as np
>>> DT = dt.Frame(np.arange(10)[20:])
>>> dt.internal.frame_integrity_check(DT)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: in column 0 'C0': Assertion 'size_ > 0' failed in c/buffer.cc, line 179
```
