### ISSUE TITLE
Random attack failure for seed 5245198198137804574

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#2173]
```
Seed: 5245198198137804574

Making a frame with nrows=86, ncols=12
  types: bool=2, int=4, float=4, str=2
  missing values: 0.000
Launching an attack for 89 rounds
[02] Applying row slice (14, 85, 2) -> nrows = 36
[05] Rbinding frame with itself 1 times -> nrows = 72
[08] Selecting rows where column 0 ('Y0') is True
[08] Selecting rows where column 0 ('Y0') is True
[07] Removing rows [0, 1, 2, 3, 4, 5, 8, 9, 10, 12, 13, 14, 15, 17, 25, 26, 27, 29, 31, 32, 33, 35, 36, 37, 38, 39, 40, 45, 48, 50, 51, 55] -> nrows = 24
[06] Selecting a row list [2, -16, -17, -13, 4, 15, 2, 9, -19, -12, 16, 23, -16, -21, -3, -12, -5, -6, -21, 15, 3, -24, 18, 1, -17, 7, -12, 16, -17, -10, -24, -16] -> nrows = 32
[02] Applying row slice (3, 30, 2) -> nrows = 14
[12] Adding a range column range(-3, 25, 2) -> ncols = 13
[02] Applying row slice (None, None, 2) -> nrows = 7
[11] Cbinding frame with a numpy column -> ncols = 14
[01] Setting nrows to 12
[07] Removing rows [2, 4, 5, 6, 7, 8, 9, 10, 11] -> nrows = 3
[02] Applying row slice (None, None, None) -> nrows = 3
[15] Joining frame with itself -> ncols = 14
[07] Removing rows [0, 1, 2] -> nrows = 0
[01] Setting nrows to 1
[03] Applying column slice (12, None, -1) -> ncols = 13
[05] Rbinding frame with itself 4 times -> nrows = 5
[14] Removing columns [0, 5, 1, 8, 8, 7, 9, 0, 11] -> ncols = 6
[05] Rbinding frame with itself 2 times -> nrows = 15
[08] Selecting rows where column 4 ('Y2') is True
[08] Selecting rows where column 5 ('Y0') is True
[14] Removing columns [3, 4, 2, 0, 1] -> ncols = 1
[15] Joining frame with itself -> ncols = 1
[05] Rbinding frame with itself 6 times -> nrows = 0
[04] Cbinding frame with itself 3 times -> ncols = 4
[02] Applying row slice (0, None, 5) -> nrows = 0
[11] Cbinding frame with a numpy column -> ncols = 5
[02] Applying row slice (0, 0, 2) -> nrows = 0
[12] Adding a range column range(-4, -4) -> ncols = 6
[02] Applying row slice (0, 0, 2) -> nrows = 0
[08] Selecting rows where column 3 ('Y3') is True
[15] Joining frame with itself -> ncols = 6
[14] Removing columns [2, 4, 0, 1, 3, 1] -> ncols = 1
[02] Applying row slice (None, 0, 7) -> nrows = 0
[05] Rbinding frame with itself 1 times -> nrows = 0
[13] Setting 1 key column: [0]
[02] Applying row slice (0, 0, 4) -> nrows = 0
[10] Sorting 1 column in ascending order: [0]
[11] Cbinding frame with a numpy column -> ncols = 2
[04] Cbinding frame with itself 1 times -> ncols = 4
[11] Cbinding frame with a numpy column -> ncols = 5
[11] Cbinding frame with a numpy column -> ncols = 6
[13] Setting 1 key column: [5]
[12] Adding a range column range(16, 16, 3) -> ncols = 7
[04] Cbinding frame with itself 3 times -> ncols = 28
[09] Replacing NA values in column 10 with -35
[04] Cbinding frame with itself 2 times -> ncols = 84
[04] Cbinding frame with itself 2 times -> ncols = 252
[05] Rbinding frame with itself 5 times -> nrows = 0
[11] Cbinding frame with a numpy column -> ncols = 253
[02] Applying row slice (None, None, 3) -> nrows = 0
[02] Applying row slice (None, None, None) -> nrows = 0
[09] Replacing NA values in column 11 with -37
[16] Creating a shallow copy of a frame
[10] Sorting 1 column in ascending order: [28]
[10] Sorting 2 columns in ascending order: [246, 168]
[01] Setting nrows to 1
[03] Applying column slice (None, None, 2) -> ncols = 127
[10] Sorting 2 columns in ascending order: [14, 46]
[07] Removing rows [0] -> nrows = 0
[05] Rbinding frame with itself 4 times -> nrows = 0
[10] Sorting 1 column in ascending order: [28]
[11] Cbinding frame with a numpy column -> ncols = 128
[11] Cbinding frame with a numpy column -> ncols = 129
[09] Replacing NA values in column 10 with -38
[05] Rbinding frame with itself 1 times -> nrows = 0
[16] Creating a shallow copy of a frame
Traceback (most recent call last):
  File "tests/random_attack.py", line 978, in <module>
    ra.attack()
  File "tests/random_attack.py", line 115, in attack
    self.attack_frame(frame)
  File "tests/random_attack.py", line 130, in attack_frame
    action(self, frame)
  File "tests/random_attack.py", line 349, in shallow_copy
    frame.shallow_copy()
  File "tests/random_attack.py", line 914, in shallow_copy
    self.df_deep_copy = copy.deepcopy(self.df)
  File "/Users/pasha/py36/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
RuntimeError: Invalid data access for a virtual column
```

**Comment by st-pasha** [comment]
The issue seems to be that `NpMasked_ColumnImpl` columns do not materialize properly.

**Comment by st-pasha** [comment]
Specifically, this affects 0-size numpy arrays:
```python
>>> import datatable as dt
>>> import numpy as np
>>> DT = dt.Frame(np.ma.array(range(10), mask=[False,True]*5)[10:5])
>>> DT.to_jay()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Invalid data access for a virtual column
```
