### ISSUE TITLE
import datatable causes errors while using dask distributed

### ISSUE THREAD

**Issue by santhisenan** [h2oai/datatable#2312]
- Did you find a bug in datatable, or maybe the bug found you?
  Creating a distributed scheduler using `Client()` after importing [datatable](https://github.com/h2oai/datatable) library causes 
  > ValueError: I/O operation on closed file
  > distributed.utils - ERROR - addresses should be strings or tuples, got None

- How to reproduce the bug?
   - Install dask distributed using `pip install dask distributed --upgrade`
   - Save the following code snippet as a file and run it from terminal.
    ```
    import datatable as dt
    from dask.distributed import Client
    client = Client()
    ```

- Your environment?
  Python version: 3.7.4
  Datatable version: 0.10.1
  OS: MacOS Catalina version 10.15.1

- Stack trace
**Full stack trace: [log.txt](https://github.com/dask/distributed/files/4082812/log.txt)**

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/forkserver.py", line 261, in main
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/forkserver.py", line 261, in main
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/forkserver.py", line 261, in main
    old_handlers)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/forkserver.py", line 297, in _serve_one
    old_handlers)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/forkserver.py", line 297, in _serve_one
    code = spawn._main(child_r)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    old_handlers)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/forkserver.py", line 297, in _serve_one
    code = spawn._main(child_r)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    code = spawn._main(child_r)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    run_name="__mp_main__")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 263, in run_path
    run_name="__mp_main__")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 263, in run_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    pkg_name=pkg_name, script_name=fname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    pkg_name=pkg_name, script_name=fname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    run_name="__mp_main__")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 263, in run_path
    mod_name, mod_spec, pkg_name, script_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/santhisenan/Documents/projects/test/dask/bug-test/test.py", line 4, in <module>
    exec(code, run_globals)
  File "/Users/santhisenan/Documents/projects/test/dask/bug-test/test.py", line 4, in <module>
    pkg_name=pkg_name, script_name=fname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    import datatable as dt
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/__init__.py", line 27, in <module>
    mod_name, mod_spec, pkg_name, script_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    from .fread import fread, GenericReader, FreadWarning, _DefaultLogger
    import datatable as dt
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/fread.py", line 17, in <module>
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/__init__.py", line 27, in <module>
    exec(code, run_globals)
  File "/Users/santhisenan/Documents/projects/test/dask/bug-test/test.py", line 4, in <module>
    from datatable.utils.typechecks import (TValueError, TTypeError,
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/utils/typechecks.py", line 14, in <module>
    import datatable as dt
    from .fread import fread, GenericReader, FreadWarning, _DefaultLogger
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/__init__.py", line 27, in <module>
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/fread.py", line 17, in <module>
    from datatable.utils.terminal import term
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/utils/terminal.py", line 160, in <module>
    from .fread import fread, GenericReader, FreadWarning, _DefaultLogger
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/fread.py", line 17, in <module>
    from datatable.utils.typechecks import (TValueError, TTypeError,
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/utils/typechecks.py", line 14, in <module>
    term = Terminal()
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/utils/terminal.py", line 55, in __init__
    from datatable.utils.typechecks import (TValueError, TTypeError,
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/utils/typechecks.py", line 14, in <module>
    from datatable.utils.terminal import term
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/utils/terminal.py", line 160, in <module>
    from datatable.utils.terminal import term
    self._blessed_term = blessed.Terminal()
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/utils/terminal.py", line 160, in <module>
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/blessed/terminal.py", line 165, in __init__
    term = Terminal()
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/utils/terminal.py", line 55, in __init__
    term = Terminal()
    self._keyboard_fd = sys.__stdin__.fileno()
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/utils/terminal.py", line 55, in __init__
ValueError: I/O operation on closed file
    self._blessed_term = blessed.Terminal()
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/blessed/terminal.py", line 165, in __init__
    self._blessed_term = blessed.Terminal()
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/blessed/terminal.py", line 165, in __init__
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/forkserver.py", line 261, in main
    self._keyboard_fd = sys.__stdin__.fileno()
ValueError: I/O operation on closed file
    self._keyboard_fd = sys.__stdin__.fileno()
ValueError: I/O operation on closed file
    old_handlers)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/forkserver.py", line 297, in _serve_one
    code = spawn._main(child_r)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/santhisenan/Documents/projects/test/dask/bug-test/test.py", line 4, in <module>
    import datatable as dt
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/__init__.py", line 27, in <module>
    from .fread import fread, GenericReader, FreadWarning, _DefaultLogger
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/fread.py", line 17, in <module>
    from datatable.utils.typechecks import (TValueError, TTypeError,
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/utils/typechecks.py", line 14, in <module>
    from datatable.utils.terminal import term
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/utils/terminal.py", line 160, in <module>
    term = Terminal()
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/datatable/utils/terminal.py", line 55, in __init__
    self._blessed_term = blessed.Terminal()
  File "/Users/santhisenan/.sm-dask/lib/python3.7/site-packages/blessed/terminal.py", line 165, in __init__
    self._keyboard_fd = sys.__stdin__.fileno()
ValueError: I/O operation on closed file
distributed.utils - ERROR - addresses should be strings or tuples, got None

**Comment by st-pasha** [comment]
This seems to be not the problem with datatable per se, but rather with our dependency `blessed`. Note that we're planning to eliminate this dependency in the next release (#1677).

The reason for the error is that Dask is using multiprocessing module, which attempts to fork the process. One common recommendation for writing python scripts to use with `multiprocessing` is to guard them with `if __name__ == "__main__"` clause. Thus, if you change your script to 
```
if __name__ == "__main__":
    import datatable as dt
    from dask.distributed import Client
    client = Client()
```
then it no longer throws an error.

**Comment by santhisenan** [comment]
@st-pasha You are right.

I will close the issue.
