### ISSUE TITLE
[DOC] Preview Error with Sphinx/DocUtils

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#2498]
### Environment 

* **Ubuntu 20.04**
* **Installed from source (pip)**
* **Version 0.10.1**
* **Python version (3.8.3)**

### Description

Hi @st-pasha , This is in reference to #2485.
I want to add examples for ``fread``. However, when I tried working on the documentation in ``vscode``,  I get this error : 

```Detailed error message
Error
Command failed: "/home/sam/miniforge3/envs/datatable/bin/python" -m sphinx -b html . "/home/sam/github_cloned_projects/datatable/docs/_build/html"
/home/sam/github_cloned_projects/datatable/docs/conf.py:236: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
  app.add_stylesheet("code.css")

Exception occurred:
  File "/home/sam/miniforge3/envs/datatable/lib/python3.8/site-packages/sphinx/domains/python.py", line 1194, in clear_doc
    if obj.docname == docname:
AttributeError: 'tuple' object has no attribute 'docname'
The full traceback has been saved in /tmp/sphinx-err-bgfm4v_e.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at . Thanks!

Error: Command failed: "/home/sam/miniforge3/envs/datatable/bin/python" -m sphinx -b html . "/home/sam/github_cloned_projects/datatable/docs/_build/html"
/home/sam/github_cloned_projects/datatable/docs/conf.py:236: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
  app.add_stylesheet("code.css")

Exception occurred:
  File "/home/sam/miniforge3/envs/datatable/lib/python3.8/site-packages/sphinx/domains/python.py", line 1194, in clear_doc
    if obj.docname == docname:
AttributeError: 'tuple' object has no attribute 'docname'
The full traceback has been saved in /tmp/sphinx-err-bgfm4v_e.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at . Thanks!

	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:203:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

/home/sam/github_cloned_projects/datatable/docs/conf.py:236: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
  app.add_stylesheet("code.css")

Exception occurred:
  File "/home/sam/miniforge3/envs/datatable/lib/python3.8/site-packages/sphinx/domains/python.py", line 1194, in clear_doc
    if obj.docname == docname:
AttributeError: 'tuple' object has no attribute 'docname'
The full traceback has been saved in /tmp/sphinx-err-bgfm4v_e.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at . Thanks!
More Information
Diagnostics information has been written to OUTPUT | reStructuredText panel.

The troubleshooting guide can be found at

https://docs.restructuredtext.net/articles/troubleshooting.html
```

I cannot preview changes while working on the documentation. What do you suggest?

**Comment by st-pasha** [comment]
Sphinx had some breaking API changes recently, and we're not compatible with their newest version of the library yet. While this is something that we want to fix at some point, for now I'd recommend to install Sphinx version before 3.0.

**Comment by samukweku** [comment]
Thanks @st-pasha ! I'll do just that
