### ISSUE TITLE
[FR] fread should read excel files from url

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#2631]
Attempted reading an excel file from a url and it failed. I believe it is something that could be implemented.

```python
url = 'https://github.com/samukweku/Extracting-Data-from-Excel-with-Python/blob/master/names.xlsx'

---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-143-984be964b066> in <module>
----> 1 fread(url)

IOError: https://github.com/samukweku/Extracting-Data-from-Excel-with-Python/blob/master/names.xlsx is an HTML file. Please open it in a browser and then save in a plain text format.
```

I know `xlrd` supports reading from a url; not sure if there is a design decision of not being able to read excel files from a url.

**Comment by st-pasha** [comment]
Hmm, this is strange: when I try to open this file with fread, I get error 404:
```
>>> dt.fread(url)
  0% |                                                  | Downloading https://github.com/samukweku/Extracting-Data-from-Excel-with-Python/blob/master/names.xlsx?raw=true [error]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by samukweku** [comment]
Yes. When I attempt it with pandas it reads fine.
