### ISSUE TITLE
``pip install datatable`` broken on version 1.0.0

### ISSUE THREAD

**Issue by scnerd** [h2oai/datatable#3071]
- Did you find a bug in datatable, or maybe the bug found you?
Installation directly from pip no longer works as expected, particularly within Docker.

- How to reproduce the bug?
```
$ docker run --rm -it docker run --rm -it continuumio/miniconda3 bash
$ pip install datatable==1.0.0
```

- What was the expected behavior?
``datatable`` should be installed successfully.

- Your environment?
``continuumio/miniconda3`` docker image (I tested in ``continuumio/miniconda3@sha256:1d17ca42494bf4d99030845e05376eb2d246b1ed5ee61afbbf2d1f8fff4f5bba``)

- Tag the issue with `[bug]` or `[segfault]` (depending on whether it crashes
  Python or not).
`[bug]`

- Notes

This works correctly for ``"datatable<1.0.0"``.

The first error in an otherwise unmodified docker container is:

```
Collecting datatable==1.0.0
  Downloading datatable-1.0.0.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 370 kB/s
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python /opt/conda/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpqz4iv8v2
         cwd: /tmp/pip-install-jnzw78_5/datatable
...
    RuntimeError: Suitable C++ compiler cannot be determined. Please specify a compiler executable in the `CXX` environment variable.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python /opt/conda/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpqz4iv8v2 Check the logs for full command output.
```

To fix this, I ran:

```
apt-get update
apt-get install -y build-essential
```

I then get the following error:

```
Collecting datatable==1.0.0
  Using cached datatable-1.0.0.tar.gz (1.1 MB)
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python /opt/conda/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp73hx27vz
         cwd: /tmp/pip-install-h7lzpwsa/datatable
...
    ==== BUILD ====
    [1] Loading previous state from file build/build/.xbuild
        The file does not exist
        All source files will be recompiled
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'ext' has no attribute 'prepare_metadata_for_build_wheel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/tmp/pip-install-h7lzpwsa/datatable/ci/ext.py", line 587, in build_wheel
        so_file = build_extension(cmd=("debug" if debug_wheel else "build"),
      File "/tmp/pip-install-h7lzpwsa/datatable/ci/ext.py", line 360, in build_extension
        ext.build()
      File "/tmp/pip-install-h7lzpwsa/datatable/ci/xbuild/extension.py", line 439, in build
        self._run_prebuild_triggers()
      File "/tmp/pip-install-h7lzpwsa/datatable/ci/xbuild/extension.py", line 488, in _run_prebuild_triggers
        fn(self)
      File "/tmp/pip-install-h7lzpwsa/datatable/ci/ext.py", line 369, in generate_documentation
        import gendoc
    ModuleNotFoundError: No module named 'gendoc'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python /opt/conda/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp73hx27vz Check the logs for full command output.
```

``pip install gendoc`` does not resolve this error.

**Comment by oleksiyskononenko** [comment]
What is the version of pip you're using? It [should be](https://datatable.readthedocs.io/en/latest/start/install.html#prerequisites) at least `20.3`. Try upgrading your pip to the latest and see if the error persists.

**Comment by scnerd** [comment]
Looks like this image comes with ``pip==20.2.4``. (Should mention this container also comes with Python 3.8)

Upgraded to 21.1.3, installation worked after that. Thanks!

**Comment by scnerd** [comment]
I'll additionally note that this fix seems to supercede any need to install ``build-essential``. Upgrading ``pip`` appears to be all that's needed.

**Comment by oleksiyskononenko** [comment]
Yeah, because I guess that the new pip just installs datatable from the wheel and doesn't require to build the source code.
