### ISSUE TITLE
Wrong multi-column sort if one of the columns is constant string

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#3141]
```
>>> DT = dt.Frame(A=['abcd'] * 100, B=[random.choice(['a', 'b']) for _ in range(100)], C=[random.choice(['ads', 'adfv', 'adfv']) for  _  in range(100)])
>>> DT[:, dt.count(), dt.by(f.A, f.B, f.C)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: Assertion 'nradixes > 0' failed in src/core/sort.cc, line 566

>>> DT[:, dt.count(), dt.by(f.A, f.B)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: Assertion 'groupby_.last_offset() == nr' failed in src/core/expr/eval_context.cc, line 288
```
This bug likely appeared after #3135 

_Originally posted by:_ @arnocandel

**Comment by st-pasha** [comment]
Just encountered this same error in a random attack.

**Comment by st-pasha** [comment]
The problem is that the `_radix_recurse()` method was recently changed to return a boolean status, and that is not taken into account in lines 591-593 of `sort.cc`. If we used C++17 there would have been a compiler warning at least.
