### ISSUE TITLE
FR: additional data format to create Frame

### ISSUE THREAD

**Issue by Peter-Pasta** [h2oai/datatable#3156]
Hi, it would be awesome if you could integrate the following functionality, similar to pandas. 

```
from datatable import dt, f, by
import pandas as pd

list_dict = [
    {'a': 1, 'b': 2},
    {'a': 1, 'b': 2},
    {'a': 1, 'b': 2}
]

df = pd.DataFrame(list_dict)
print(df)

Out:
   a  b
0  1  2
1  1  2
2  1  2

DT = dt.Frame(list_dict) # datable doesn't accept this data format 
```

Thank you!

**Comment by st-pasha** [comment]
Huh? Works for me just fine:
```python
>>> import datatable as dt
>>> list_dict = [
...     {'a': 1, 'b': 2},
...     {'a': 1, 'b': 2},
...     {'a': 1, 'b': 2}
... ]
>>> dt.Frame(list_dict)
   |    a      b
   | int8  int32
-- + ----  -----
 0 |    1      2
 1 |    1      2
 2 |    1      2
[3 rows x 2 columns]
```
Could you maybe post the error that you're encountering?

**Comment by Peter-Pasta** [comment]
This is the error:

```
Traceback (most recent call last):
  File "/Users/v/Library/Mobile Documents/com~apple~CloudDocs/Python/Projects/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-31-471dbebe15c4>", line 1, in <module>
    DT = dt.Frame(dictionary)
datatable.exceptions.TypeError: Cannot create column from a python list: element at index 0 is of type <class 'list'>. If you meant to create a column of type obj64, then you must request this type explicitly
```

**Comment by st-pasha** [comment]
Can you `print(dictionary)` then? It might not have the format that you expect.

**Comment by Peter-Pasta** [comment]
I see what the issue was. Some values in the dict are lists. This causes the error in datatable but not in pandas. 

```
list_dict = [
    {'a': [1, 1], 'b': 2},
    {'a': 1, 'b': 2},
    {'a': 1, 'b': 2}
]

df = pd.DataFrame(list_dict)  # works
DT = dt.Frame(list_dict)  # convert list to string first
```

Sorry for opening this issue.

**Comment by st-pasha** [comment]
There is no valid supertype for values `1` and `[1, 1]`, other than the object type. Datatable will not create object columns automatically though (in order to avoid possible type errors). Instead, this can be requested specifically:
```
dt.Frame(list_dict, types={'a': object})
```
