### ISSUE TITLE
[bug] Can't assign a list of values to a column - is this expected behavior?

### ISSUE THREAD

**Issue by kevinanewman** [h2oai/datatable#3438]
- Did you find a bug in datatable, or maybe the bug found you?
  Seemingly unexpected behavior when attempting to create a new column and assign values from a list or tuple when it works when assigning a range() or numpy  #Array

- How to reproduce the bug?
  **This part is the most important**. Please provide a code snippet which, when
  executed in console, demonstrates the problem. If necessary, attach any data
  files to the issue.

### fail using list of values
```
import datatable as dt
import numpy as np

DT1 = dt.Frame({'A': [1, 2, 3]}). # create single-column Frame from list of values SUCCESS
DT1['B'] = [4, 5, 6]  # create new column from list of values FAIL
```

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
datatable.exceptions.ValueError: The LHS of the replacement has 1 columns, while the RHS has 3 replacement expressions

### fail using tuple of values
`DT1['B'] = (4, 5, 6)  # FAIL`

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
datatable.exceptions.ValueError: The LHS of the replacement has 1 columns, while the RHS has 3 replacement expressions

### fail using update() and list of values
`DT1[:, update(B=[7, 8, 9])]  # FAIL`

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
datatable.exceptions.ValueError: The LHS of the replacement has 1 columns, while the RHS has 3 replacement expressions

### success using np.array() and range()
```
DT1['B'] = np.array([4, 5, 6])  # SUCCESS
DT1['C'] = range(3)  # SUCCESS
print(DT1)

DT1
   |     A      B      C
   | int32  int64  int32
-- + -----  -----  -----
 0 |     1      4      0
 1 |     2      5      1
 2 |     3      6      2
[3 rows x 3 columns]
```

- What was the expected behavior?
  In case it is not obvious, please tell us what result should your code
  produce.
 
as above

- Your environment?
  What is your datatable version, python version, and operating system?

datatable version 1.0.0, python 3.8 (x86), macOS 13.2.1 (22D68)
and also
datatable version 1.1.0a0+build.1677978121.kevinnewman, python 3.9 (M1 ARM), macOS 13.2.1 (22D68)

- Tag the issue with `[bug]` or `[segfault]` (depending on whether it crashes
  Python or not).

[bug]

- Thank you for contributing, and sorry for the inconvenience.

**Comment by oleksiyskononenko** [comment]
I don't see we ever claimed it is possible to assign a list of python primitives to a frame column: https://datatable.readthedocs.io/en/latest/api/frame/__setitem__.html

But if you do 
```python
DT1['B'] = dt.Frame([4, 5, 6])
```

this will actually work.

**Comment by oleksiyskononenko** [comment]
@kevinanewman Yes, I don’t really know why this is not supported yet, may be there was a reason. Could also be it was just missed, because we do support assigning scalars or numpy arrays/ranges (that looks undocumented).

No need to close this issue, just rename it and update the text, so that it is clear this is FR and not a bug.

**Comment by kevinanewman** [comment]
Ok, I updated the title and revised the original post to make it consistent with a feature request.

Thank you!
