### ISSUE TITLE
Regression: cannot read Mushroom.gz file

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#947]
```
>>> dt.fread("https://s3.amazonaws.com/h2o-public-test-data/fread/Mushroom.gz", verbose=True)
[1] Prepare for reading
  Input is a URL.
  Using default 8 threads
  sep = <auto-detect>
  Decimal separator = '.'
  Quote char = (")
  show_progress = True
  na_strings = ["NA"]
  strip_whitespace = True
  skip_blank_lines = False
  File "/var/folders/k9/mxm_jrl50m75kmgvdk9_wlh00000gp/T/tmp8ietxe4w/tmp5zeiqnpt" opened, size: 39670
  LF character (\n) found in input, \r-only newlines will not be recognized
[2] Detect separator, quoting rule, and ncolumns
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pasha/github/datatable/datatable/fread.py", line 60, in fread
    return freader.read()
  File "/Users/pasha/github/datatable/datatable/fread.py", line 638, in read
    _dt = core.gread(self)
AssertionError: Assertion 'firstJumpEnd && topQuoteRule >= 0' failed in c/csv/fread.cc, line 251
```

**Comment by st-pasha** [comment]
Ok, on further investigation this is not a regression.

1. The URL points to a `.gz` file, and currently we are only able to determine if file is an archive based on its extension. Thus, any content retrieved from a URL is assumed to be a plain text.
2. When parsing a binary file, in assertion `firstJumpEnd && topQuoteRule >= 0` both conditions fail. Thus, "topQuoteRule" logic is not the culprit here: the assert was failing before too.
3. The reason the assert fails is because `ctx.countfields()` returns `-1` for every combination of `sep/quoteRule`. This happens because of NUL bytes: a string parser stumbles upon those and cannot parse.

Thus, this issue is directly related to #790.

Another problem is what happens in production, when `xassert`s are turned off? We proceed with parsing the file while having `firstJumpEnd=NULL` and `topQuoteRule=-1`, which won't work well...
